### ISSUE TITLE
Add support for swing/air direction

### ISSUE THREAD

**Issue by tmelliott** [scottyphillips/mitsubishi_echonet#11]
At the [bottom of page 100](https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_F_en/SpecAppendixF_e.pdf) there's info for swing/air direction&mdash;it would be amazing if this could be included!! For use in home assistant so would also need the appropriate updates over on [mitsubishi_hass](https://github.com/scottyphillips/mitsubishi_hass) at some stage (thanks for what you've got so far, btw!). I've had a look around your code but my python isn't nearly good enough to even try submitting a PR 😬

**Comment by scottyphillips** [comment]
Hi there, yes the ECHONET call is fairly straightforward for both automatic operation and manual settings of the airflow direction both horizontal and vertical and yes I can implement for you soonish when I am not so busy. Maybe within a week or so. Looks like the EPC codes of interest are 0xA3, 0xA4 and 0xA5

The HASS component - looks like we can only implement automatic swing modes (https://developers.home-assistant.io/docs/core/entity/climate/#swing-modes) and you are not going to have fine grained control over the setting of the airflow. According to the developer docs - Swing mode can only really be set automatic or off for horizontal and vertical (or both). That can be done as well, but i will be adhering to the HA docs in that case, and won't be adding in any bespoke functionality to manually control the airflow direction.  

I will work on the missing functionality in the library first and we can test the automatic swing operation in the first instance which is what HA supports. 

I haven't implemented yet it because my system is ducted (no swing mode!) :-)

**Comment by scottyphillips** [comment]
Can you do me a favour - clone this repo, run 'example.py' from the command line and dump the entire output here so I can work out exactly what EPC codes your HVAC setup supports?

**Comment by tmelliott** [comment]
No worries about hass's limitations - if I can control it via this library, I should be able to come up with some kind of workaround ... 

Mine only does vertical swing. Here's the output:
```
$ python3 example.py 
Discovering Anything..
Group: Air conditioner-related device group
Code: Home air conditioner
Instance: 1
ECHONET lite node discovered at 1.2.3.4 - Home air conditioner class
ECHONET node 1.2.3.4 available Get properties:
{'Standard version information': 130, 'Set property map': 158, 'Measured value of room temperature': 187, 'Identification number': 131, 'Operation mode setting': 176, 'Manufacturer code': 138, 'Set temperature value': 179, 'Air flow direction (vertical) setting': 164, 'Operation power-saving': 143, 'Air flow rate setting': 160, 'Status change announcement property map': 157, 'Automatic swing of air flow setting': 163, 'Get property map': 159, 'Measured outdoor air temperature': 190, 'Automatic control of air flow direction setting': 161, 'Manufacturers fault code': 134, 'Installation location': 129, 'Fault status': 136, 'Operation status': 128, 'Fault description': 137}
ECHONET node 1.2.3.4 available Set properties:
{'Operation power-saving': 143, 'Operation status': 128, 'Automatic control of air flow direction setting': 161, 'Installation location': 129, 'Set temperature value': 179, 'Air flow direction (vertical) setting': 164, 'Automatic swing of air flow setting': 163, 'Air flow rate setting': 160, 'Operation mode setting': 176}
```

**Comment by scottyphillips** [comment]
Can you please checkout the 'swingMode' branch and test for me? 'example.py' has been updated with some get commands and there is some commented out set commands below you can play around with too..

**Comment by tmelliott** [comment]
Get methods work, and setting to vertical swing mode works. The `'off'` setting should instead be `'not-used'`:
```
>>> node.setSwingMode('off')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/emperor/projects/hass/mitsubishi_echonet/mitsubishi_echonet/__init__.py", line 528, in setSwingMode
    if self.setMessage(0xA3, SWING_MODE[swing_mode]):
KeyError: 'off'
>>> node.setSwingMode('not-used')
True
```
For consistency, I'd suggested changing line 100 of `functions.py` (`not-used` instead of `off`) so the get method returns the same value as one would specify for the set method.

Line 25 of `example.py` should be `'not-used'` instead of `'off`.

I know this won't be used in HASS but `node.setAirflowVert('upper')` also works :+1: 

I can't check the vertical swing. From a quick look it all seems fine.

**Thanks heaps for doing this!!**

PS: if you get on to updating `mitsubishi_hass`, let me know if you want help testing it there.

**Comment by scottyphillips** [comment]
Cheers, Yeah I was tossing up whether to change 'not-used' to 'off' (the spec refers to the op code as 'not-used'). Ive decided to keep it as per the ECHONET spec as suggested.

I'll sit on this for a week or so before merging into the main branch so I can update the docs and give it a new version for PyPi. HACS code will be updated next week I anticipate. In the mean time feel free to keep testing.

**Comment by khcnz** [comment]
I've got units that support vertical and horizontal swing. Would you like me to test anything specifically? 

Looks like you did 90% of the work for the horizontal swing as well, I can try finish that off for ya for a get/set?

**Comment by scottyphillips** [comment]
Yeah go for it. I haven’t merged the branch yet but if you want to contribute some code that would be much appreciated. Just make the changes to the swing branch and I’ll approve them.
