### ISSUE TITLE
Compatibility with MAC-567IF-E

### ISSUE THREAD

**Issue by lukas-schwab** [scottyphillips/mitsubishi_echonet#19]
I own several air conditioners with a seperate wifi interface (MAC-567IF-E) but when I try to discover devices with 
```
aircons = mit.discover('Home air conditioner')
aircon = aircons[0]
```
an empty array is returned. Why could this be? I'm connected to the same network. Is this specific interface just not supported?

I'd appreciate any help!

Edit: I found the pymelcloud pip package which turned out to fulfill all my needs.

**Comment by scottyphillips** [comment]
MAC-567IF-E is not supported sorry as it does not support the ECHONET standard.
