### ISSUE TITLE
Home Assistant 0.96 breaks everything...

### ISSUE THREAD

**Issue by scottyphillips** [scottyphillips/mitsubishi_echonet#5]
Not that I have even installed HA 0.96 yet but it is clear from the release notes that its going to break all the existing climate integrations. What is probably going to happen is that I will split this code into two seperate projects - this will remain as the generic library, and I will create a seperate project for the HA integration.

Likely will use the current Daikin component as the basis for rebuilding the component. Thanks for all the additional work HA Devs! :-)

**Comment by gcorgnet** [comment]
Upgraded this morning to 0.96 and discovered (too late) that this integration was broken.
Looks like you're onto it! Thanks for that.
Happy to help with some testing if required.

**Comment by scottyphillips** [comment]
Updated custom config is ready for testing. Because I am fundamentally a lazy coder I simply updated the component in accordance with https://github.com/home-assistant/home-assistant/pull/23899

**Comment by gcorgnet** [comment]
Legend! Thanks for sorting that out so quickly. Works for me now on 0.96.3.

**Comment by scottyphillips** [comment]
working for @gcorgnet and now me in production so closing issue
