### ISSUE TITLE
IDEA : Pull Mitsubishi Into It's own repo

### ISSUE THREAD

**Issue by DickSwart** [scottyphillips/mitsubishi_echonet#8]
Hi Scotty, I was wondering if you can start a new repo with just the mitsubishi custom component? And then make it so we can import it through [Hacs (Home Assistant Community Store)](https://github.com/custom-components/hacs). I'm more than happy to help contribute.

**Comment by scottyphillips** [comment]
To be honest it has been on my to-do list for a while. Sounds like a plan.

**Comment by scottyphillips** [comment]
https://github.com/scottyphillips/mitsubishi_hass
